### ISSUE TITLE
"Item:" before item name

### ISSUE THREAD

**Issue by mervy-n** [alex3236/ItemChat#1]
Please remove the "Item:" before the item name, I can not find any way to remove this from config as It would look better if it was without the prefix, similar to the top 2

![image](https://github.com/alex3236/ItemChat/assets/94481422/54e87153-ebaf-414c-85f7-90a449557864)

**Comment by alex3236** [comment]
Thank you for the suggestion. The prefix was added to distinguish it from Vanilla messages. I will add the option to turn it off in a future release.

**Comment by mervy-n** [comment]
Hello, just wondering when this function will be added as I planned to add it quite a while ago

**Comment by alex3236** [comment]
> Hello, just wondering when this function will be added as I planned to add it quite a while ago

In a week I think. Feel free to PR if you have done it.
